@startuml

start

:Lancement du logiciel;

if(Serveur ?) is (oui) then

partition Serveur {
    :Paramétrage du serveur;
    :Autoriser les clients\nà se connecter;
    fork
        repeat
            :Attente de connexion;
            :Création d'un thread;
            :Attente de la réception\nd'une musique;
            :Demande d'ajout\nd'une musique;
            if(Déjà présente dans\nla base de données ?) is (oui) then
                :Récupération de\nla musique;
            else (non)
                :Attente fin réception;
                :Stockage dans\nle système;
            endif
            :Mise en place dans la playlist;
        repeat while(Serveur arrêté ?) is (non)

    fork again
        repeat
            :Lecture playlist;
            :Modification de la playlist\nen fonction des upvotes;
        repeat while(Serveur arrêté ?) is (non)
    end fork
}

else (non)

partition Client {
    :Recherche d'un serveur;
    :Connexion au serveur;
    repeat
        :Récupération de la playlist\nen cours de lecture;
        -[dashed]->
        :Envoi d'une musique\nAction sur la musique}
    repeat while (Connexion coupée ?) is (non)
}

endif


-[dashed]->
:Nettoyer les ressources:\nNettoyer la base de données\nNettoyer lesystème de stockage\nLibérer les ressources}

end

@enduml
