@startuml

actor serveur
database DB_locale
storage stockage_local

actor client1
actor client2

DB_locale - serveur
serveur - stockage_local

client1 <..> DB_locale

serveur <--> client1
serveur <--> client2

@enduml
