@startuml

database DB_locale
actor serveur
storage stockage_local
actor client1
actor client2

client1 <--> serveur
client2 <--> serveur

DB_locale - serveur
serveur - stockage_local

client1 <..> DB_locale

@enduml
